#ifndef CLOWNCD_COMMON_H
#define CLOWNCD_COMMON_H

#define CLOWNCD_SECTOR_RAW_SIZE 2352
#define CLOWNCD_SECTOR_HEADER_SIZE 0x10
#define CLOWNCD_SECTOR_DATA_SIZE 0x800
#define CLOWNCD_AUDIO_CHANNELS 2
#define CLOWNCD_AUDIO_FRAME_SIZE (CLOWNCD_AUDIO_CHANNELS * 2)
#define CLOWNCD_AUDIO_FRAMES_PER_SECTOR (CLOWNCD_SECTOR_RAW_SIZE / CLOWNCD_AUDIO_FRAME_SIZE)

#endif /* CLOWNCD_COMMON_H */
